EXECUTE ATUALIZAR_CLI_SEG_MERCADO (12, 2);
EXECUTE ATUALIZAR_CLI_SEG_MERCADO (15, 2);

UPDATE CLIENTE SET SEGMERCADO_ID = 2
    WHERE ID = 15;

create or replace PROCEDURE atualizar_cli_seg_mercado (
    p_ID CLIENTE.ID%type, 
    p_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%type
)
IS
    e_CLIENTE_ID_INEXISTENTE exception;
BEGIN
    UPDATE CLIENTE SET SEGMERCADO_ID = p_SEGMERCADO_ID
        WHERE ID = p_ID;
    IF SQL%NOTFOUND THEN
        RAISE e_CLIENTE_ID_INEXISTENTE;
    END IF;
    COMMIT;
EXCEPTION
    WHEN e_CLIENTE_ID_INEXISTENTE THEN
        raise_application_error(-200100, 'Cliente inexistente !!!');
END;

EXECUTE ATUALIZAR_CLI_SEG_MERCADO (15, 2);