CREATE OR REPLACE PROCEDURE incluir_segmercado
(p_ID IN SEGMERCADO.ID%type, p_DESCRICAO IN SEGMERCADO.DESCRICAO%type)
IS
BEGIN
    INSERT INTO SEGMERCADO(ID, DESCRICAO) VALUES (p_ID, UPPER(p_DESCRICAO));
    COMMIT;
END;

EXECUTE INCLUIR_SEGMERCADO(4, 'Farmaceuticos');

BEGIN
    INCLUIR_SEGMERCADO(5, 'Hoteleiros');
END;