DECLARE
    v_ID SEGMERCADO.ID%type := 3;
    v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Esportistas';
BEGIN
    INSERT INTO SEGMERCADO(ID, DESCRICAO) VALUES (v_ID, UPPER(v_DESCRICAO));
    COMMIT;
END;

DECLARE
    v_ID SEGMERCADO.ID%type := 3;
BEGIN
    DELETE FROM SEGMERCADO WHERE ID = v_ID;
    COMMIT;
END;